name: Mobile

on:
  push:
    branches:
      - "main"
  pull_request:
    branches: 
      - "*"

jobs:
    Build_Android:
      runs-on: macos-latest

      steps:
      - uses: actions/checkout@v1

      - name: Restore NuGet 
        run: |
          nuget restore

      - name: Inject Token
        env:
          TOKEN: ${{ secrets.TOKEN }}
        
        run: |
          GitHubConstantsFile='find . -name GitHubConstants.cs | head -1'
          sed -i '' "s/PersonalAccessToken = \"\"/PersonalAccessToken = \"$TOKEN\"/g" "$GitHubConstantsFile"
          sed -i '' "s/#error Missing Token/\/\/##error Missing Token/g" "$GitHubConstantsFile"          
          
      - name: Build Android App
        run: |                    
          mono /Applications/Visual\ studio.app/Contents/Resources/lib/monodevelop/bin/MSBuild/Current/bin/MSBuild.dll ./SimpleXamarinGraphQL.Android/SimpleXamarinGraphQL.Android.csproj /verbosity:normal /p:Configuration=Release     
        